### PR TITLE
Finish mobile version

### PR DESCRIPTION
**Pull request by fithamlak**
I did this by stick on the stigma template for the mobile version

### CODE REVIEW

**Review by joskalenda — CHANGES_REQUESTED** [review]
Hi @fithamlak , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

⚠️  You have submitted a project, that has no linters installed, please make sure you set them uo and resubmit your project for review



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

-----
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._ 🟢

**Review by joskalenda — CHANGES_REQUESTED** [review]
Hi @fithamlak , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

⚠️  You have submitted a project, that linters installed, as I mentioned before, maybe you have missed this lesson article about linter at microverse,  please take a step back and read this article [here](https://github.com/microverseinc/linters-config) to step ut the linters correctly and resubmit your code again



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

-----
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._ 🟢

**Comment by fithamlak** [comment]
image
 the linters are here what is the problem, and it works in locl repo

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @fithamlak, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

As mentioned by the previous reviewer, you have submitted a project that has no linters checks. whereas, as part of the [project requirements ](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md)

- Linter should be set up correctly for this repository.
- Linter result should be green, this means that the last commit has a green check mark (✅) 
- There should be no custom changes to the linter config.

However, if you need additional explanation/support concerning how to set up linters correctly  
Please, kindly visit [this FAQ](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) and schedule a 1:1 meeting with a Senior code reviewer 😊.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
